### ISSUE TITLE
bugs in subsetRep()

### ISSUE THREAD

**Issue by zhongyi960403** [rje42/MixedGraphs#1]
The function subsetRep() is not working with error:

G1 <- graphCr("1<->2<->3<->4<-5","1<-6<-5","6<-3","6<-4")
subsetRep(G1)

Error in adj(graph, v, etype = "undirected", dir = 0, inclusive = TRUE,  : 
  Unrecognised edge format

**Comment by rje42** [comment]
Sorry, I uploaded an older version of the package `MixedGraphs`. It should be fixed now!
