### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lwh97yy** [rje42/MixedGraphs#10]
I would like to ask how to draw the mixed graph obtained through this package

**Comment by rje42** [comment]
There isn't a canonical way for doing that at the moment, but a 'hack' is as follows.  First, convert the graph to a PAG adjacency matrix:
```
gr_PAG <- convert(graph, "PAG")
```
Then run the following code:
```
plot(methods::new("fciAlgo", amat=as(gr_PAG, "matrix")))
```
and, provided that `pcalg` and `Rgraphviz` are installed, it should plot `graph`.

**Comment by lwh97yy** [comment]
Thank you very much for your patience and detailed answers. I have gained a lot!
















At 2023-12-04 21:47:46, "Robin Evans" ***@***.***> wrote:

There isn't a canonical way for doing that at the moment, but a 'hack' is as follows. First, convert the graph to a PAG adjacency matrix:

gr_PAG <- convert(graph, "PAG")


Then run the following code:

plot(methods::new("fciAlgo", amat=as(gr_PAG, "matrix")))


and, provided that pcalg and Rgraphviz are installed, it should plot graph.
