### ISSUE TITLE
bug in latentProject()

### ISSUE THREAD

**Issue by zhongyi960403** [rje42/MixedGraphs#11]
> latentProject(graphCr('6 -> 2 -> 8 <- 4 -> 6 <- 3 -> 4 -> 5 <- 2','8 <- 1 -> 7'),c(2,5,6,8))
Graph with 4 vertices:  x1  x3  x4  x7  

x4 --> x3 
x3 --> x4 
x4 --> x4 
x1 --> x7 

> is_cyclic(graphCr('6 -> 2 -> 8 <- 4 -> 6 <- 3 -> 4 -> 5 <- 2','8 <- 1 -> 7'))
[1] FALSE

**Comment by rje42** [comment]
`latentProject()` is a function from `ADMGs2`.  Can you post this there please?
