### ISSUE TITLE
bugs in subsetRep()

### ISSUE THREAD

**Issue by zhongyi960403** [rje42/MixedGraphs#3]
G <- graphCr("1 - 2 - 3 - 4 - 2","1 - 3")
adj <- subsetRep(G,sort=3)
Error in subsetRep(G, sort = 3) : 
  There should not be a duplication, but something appears twice

**Comment by rje42** [comment]
This should be fixed now (notice this is not a `MixedGraphs` function, but is rather in `ADMGs2`).
