### ISSUE TITLE
addEdges()

### ISSUE THREAD

**Issue by zhongyi960403** [rje42/MixedGraphs#6]
addEdges(graphCr("1 o-o 2 o-o 3 o-o 4 o-o 1 o-o 3 o-o 5 - 2"), `undirected`=eList(c(5,4)))
works fine but

addEdges(graphCr("1 o-o 2 o-o 3 o-o 4 o-o 1 o-o 3 o-o 5 - 2",mode="adjMatrix"), `undirected`=eList(c(5,4)))
Error in if (nrow(edges[[i]]) == nv(graph)) { : 
  argument is of length zero

**Comment by rje42** [comment]
Should be solved now.  That was introduced by the previous fix, sorry!
