### ISSUE TITLE
error in addNodes()

### ISSUE THREAD

**Issue by zhongyi960403** [rje42/MixedGraphs#9]
```
G <- graphCr("1 -> 2 <-> 3 <-> 4 <- 2")
removeEdges(G,`bidirected`=eList(c(2,3)))
```
This works fine but if I apply addNodes to the graph then error occurs for removeEdges()
```
G <- graphCr("1 -> 2 <-> 3 <-> 4 <- 2")
G <- addNodes(G,1)
removeEdges(G,`bidirected`=eList(c(2,3)))
```
Error in out$edges[[etys[et[i]]]][graph$v, graph$v] : 
  subscript out of bounds

**Comment by rje42** [comment]
This should be sorted now... (The old function didn't know about `adjList`s!)
